#! /bin/sh
xrdb ~/.Xresources
compton & 
polybar top &
sxhkd &
notify_desktop & 
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap          20

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config click_to_focus       true

bspc config top_padding 35


bspc rule -a Alacritty state=floating
bspc rule -a Pinentry state=floating
bspc rule -a pinentry state=floating

feh --bg-scale ~/.wallpapers/pineapple.png &

dunst -conf /home/patrik/.config/dunst/dunstrc &

libinput-gestures-setup start
xinput set-prop 15 287 1 1
